server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: reggie_take_out # 指定应用名称：optional
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  main:
    banner-mode: off
  redis:
    host: 192.168.6.134
    port: 6379
    password: 1234
    database: 0

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射：address_book-->AddressBook
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false # 取消springboot初始输出日志
    db-config:
      id-type: ASSIGN_ID # 生成策略

reggie:
  path: E:\download_apps\IntelliJ IDEA 2022.1.3\workplace\reegie_take_out\src\main\resources\pics\