server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: reggie_take_out # 指定应用名称：optional
  main:
    banner-mode: off # 关闭spring的banner输出
    allow-bean-definition-overriding: true # 允许Bean覆盖：shardingsphere
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源：这里的配置具体体现在下面masterslave的配置上
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.85.134:3306/reggie?characterEncoding=utf-8
        username: root
        password: 1234
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.85.135:3306/reggie?characterEncoding=utf-8
        username: root
        password: 1234
    masterslave:
      # 负载均衡：读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false

  redis:
    host: 192.168.85.134
    port: 6379
    password: 1234
    database: 0
  cache:
    redis:
      time-to-live: 1800000

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射：address_book-->AddressBook
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false # 取消springboot初始输出日志
    db-config:
      id-type: ASSIGN_ID # 生成策略

reggie:
#  path: E:\download_apps\IntelliJ IDEA 2022.1.3\workplace\reegie_take_out\src\main\resources\pics\
  path: /data/songfang/apps/reegie_take_out/img/